### ISSUE TITLE
Item effects removed if item loses durability 

### ISSUE THREAD

**Issue by kawaii** [IM-IgniteDEV/2Devs-EquipmentEffects#1]
If the item you've applied an effect to in the ItemStack loses even a single point of durability, it is no longer considered the correct item and you shortly lose whatever effects were applied once the plugin re-checks player inventories.

**Comment by IM-IgniteDEV** [comment]
[https://github.com/IM-IgniteDEV/2Devs-EquipmentEffects/commit/7e20cb695acc6a6d94bbe5e991312caaf25acf38](url)
