### ISSUE TITLE
Effects lost on death

### ISSUE THREAD

**Issue by oliver408i** [IM-IgniteDEV/2Devs-EquipmentEffects#5]
HOW TO REPRODUCE:
1. Use /eea give DEFAULT to get the default item for the test
2. Turn on keep inventory
3. (optional) Set your spawn
4. Kill yourself (/kill)
5. Respawn
Expected: The effect should be re-given on respawn
Instead: The effect does not reapply even though the boots are still in the feet slot

PLUGIN VERSION: 1.5.5 (Stable)
Server Version: Latest paper 1.18

**Comment by IM-IgniteDEV** [comment]
It was fixed day after you created issue but I forgot to close it.
